CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "profile_id" int UNIQUE NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "profile" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar,
  "last_name" varchar,
  "phone_number" varchar
);

CREATE TABLE "movies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "genre_id" int NOT NULL,
  "duration" int NOT NULL,
  "release_date" date NOT NULL,
  "director_id" int NOT NULL,
  "cast_id" int NOT NULL,
  "synopsis" text,
  "image" varchar,
  "backdrop_image" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "movie_cast" (
  "movie_id" int,
  "cast_id" int
);

CREATE TABLE "cast" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "movie_genre" (
  "movie_id" int,
  "genre_id" int
);

CREATE TABLE "genres" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "directors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "schedules" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "movie_id" int NOT NULL,
  "cinema_id" varchar NOT NULL,
  "date" date NOT NULL,
  "start_time" time NOT NULL,
  "price" int NOT NULL
);

CREATE TABLE "cinemas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "city_id" int NOT NULL
);

CREATE TABLE "city" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "seats" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "seat_code" varchar NOT NULL
);

CREATE TABLE "orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "schedule_id" int NOT NULL,
  "payment_method_id" int NOT NULL,
  "total_price" int NOT NULL,
  "payment_status" varchar,
  "full_name" varchar NOT NULL,
  "email" varchar NOT NULL,
  "phone" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "payment_method" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "order_items" (
  "order_id" int NOT NULL,
  "seat_id" int NOT NULL
);

CREATE TABLE "subscribes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firstname" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("profile_id") REFERENCES "profile" ("id");

ALTER TABLE "schedules" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("id");

ALTER TABLE "movie_genre" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("id");

ALTER TABLE "movie_genre" ADD FOREIGN KEY ("genre_id") REFERENCES "genres" ("id");

ALTER TABLE "directors" ADD FOREIGN KEY ("id") REFERENCES "movies" ("director_id");

ALTER TABLE "movie_cast" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("id");

ALTER TABLE "movie_cast" ADD FOREIGN KEY ("cast_id") REFERENCES "cast" ("id");

ALTER TABLE "schedules" ADD FOREIGN KEY ("cinema_id") REFERENCES "cinemas" ("id");

ALTER TABLE "city" ADD FOREIGN KEY ("id") REFERENCES "cinemas" ("city_id");

ALTER TABLE "payment_method" ADD FOREIGN KEY ("id") REFERENCES "orders" ("payment_method_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("schedule_id") REFERENCES "schedules" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("seat_id") REFERENCES "seats" ("id");

